### ISSUE TITLE
SonarQube open source edition

### ISSUE THREAD

**Issue by agolomoodysaada** [error418/swingletree#29]
Will there be support for the open source edition of Sonarqube?

**Comment by error418** [comment]
Swingletree should be usable with the OSS-Edition of SonarQube. However, features like Branch analysis, which come with the Developer Edition of SonarQube, will not be available.

Can you please elaborate which features you would like to see, or what kind of development workflow you have in mind?

**Comment by agolomoodysaada** [comment]
I'm trying to get branch analysis and integration with the Github Checks API from the OSS version.

**Comment by error418** [comment]
I am afraid Branch analysis is only available with the Developer Edition of SonarQube (https://www.sonarsource.com/plans-and-pricing/). The OSS version is not shipped with the SonarQube branch plugin and would therefore not fit into your workflow.

**Comment by error418** [comment]
Closing this issue for now - feel free to reopen it, if you have further questions
